// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

export {
    ACROSS_STATION_MAX_DEG,
    ACROSS_STATION_P99_MAX_DEG,
    ALONG_JOINT_MAX_DEG,
    ASPECT_EVERYWHERE_MAX,
    ASPECT_ROUND_MAX,
    applyPlantarBandZ,
    applyTangentBandZ,
    assertFilletStation,
    assertOutsideRound,
    assertT0ClearsSheet,
    BAND_INSET_MIN_MM,
    BEZIER_HANDLE_FRAC,
    bLoopOutwardNormal,
    CHORD_RISE_MAX_DEG,
    COLUMN_PLANARITY_LIMIT_MM,
    COS_T_MIN,
    type ColumnFrame,
    type ColumnQuality,
    columnHeading,
    constructArcLineArc,
    constructFillet,
    constructOutsideRound,
    constructSweepRule,
    DPHI_L_MAX_DEG,
    estimateBandInsetMm,
    evalCubicBezier,
    FILLET_ASSERT_EPS,
    FILLET_B_MAX_DEG,
    FILLET_B_MIN_DEG,
    FILLET_LAST_ROW_FRAC,
    FILLET_PSI_MAX_DEG,
    FILLET_PSI_MIN_DEG,
    FILLET_R_CAP_MM,
    FILLET_STEP_MAX_DEG,
    FOREFOOT_INSET_MM,
    FRAME_ANGLE_LIMIT_DEG,
    FRAME_SMOOTH_ITERS,
    filletCenterAndF,
    filletPathTangents,
    filletRadiusMm,
    G1_MAX_DEG,
    HANDLE_CHORD_CAP,
    HEADING_MAX_DEG,
    headingAllowanceDeg,
    incidentFaceTangent,
    inwardOfOutline,
    LAST_FILLET_S_MIN_MM,
    LAST_FILLET_Z_MIN_MM,
    LINE_MAX_STEP_MM,
    lastFilletCMinMm,
    lastFilletDLRad,
    lastFilletPhis,
    lastFilletR2MinMm,
    limitNormalSteps,
    MERGE_ROW_MM,
    MIN_EDGE_MM,
    MIN_LINE_MM,
    type MinWallClamp,
    N_TOP_MAX_DEG,
    N_TOP_PATCH_MM,
    NEIGHBOUR_SPACING_RATIO,
    nTopFromSheetSlope,
    OUTLINE_STATION_SPACING_MM,
    offPlaneMm,
    periodicGaussian,
    plantarFrameAt,
    R_CHANGE_MAX_PCT,
    R_SMOOTH_FRAC,
    R2_CHANGE_MAX_PCT,
    R2_RATE_LIMIT_PCT,
    ROUND_JOINT_MAX_DEG,
    ROUND_SWEEP_SPLIT_DEG,
    rateLimitClosed,
    rateLimitClosedDown,
    rimOverhangMm,
    rotateColumnAboutB,
    rowPieceId,
    SCALAR_SMOOTH_SIGMA_MM,
    SEAM_B_FALLBACK_DEG,
    SEAM_B_LIMIT_DEG,
    SIDEWAYS_LIMIT_MM,
    SIGNED_FOLD_MAX_DEG,
    STATION_GAP_MULT,
    STEEP_SHEET_DEG,
    sampleByArcLength,
    sampleInPlaneSlope,
    sheetSlopeFromNormal,
    sizedArcRows,
    slopeFromSheetPlane,
    smoothRoundEndAngles,
    squareHeadingToB,
    summarizeWallBands,
    T0_LEAD_DROP_MM,
    T0_PIN_DEG,
    TOE_SPACING_EXTENT_FRAC,
    TOP_CLEARANCE_DEG,
    t0FromSheetSlope,
    t0LeadQ,
    t0TargetRad,
    tangentBandZ,
    topRoundRowCount,
    U_BANDS,
    type WallBandRow,
    WELD_MM,
    wallStartTiltRad,
} from "./bezier-column";
export {
    assertCutInOnHighRimSide,
    closedSignedCurvature,
    countClosedInflections,
    fairInsetMm,
    fairLateralInsetMm,
    INFLECTION_K_EPS,
    INFLECTION_MIN_ARC_MM,
    LATERAL_K_SLACK,
    type MedialYSign,
    medialYSignFromPattern,
    medialYSignFromTopRim,
    PATTERN_ARCH_INSET_MM,
    PATTERN_BLEND_MM,
    PATTERN_CONTROL_COUNT,
    PATTERN_FEATURE_COUNT,
    PATTERN_FOREFOOT_INSET_MM,
    PATTERN_HEEL_INSET_MM,
    PATTERN_HEEL_LATERAL_INSET_MM,
    PATTERN_INSET_MM,
    PATTERN_MAX_DKDS,
    PATTERN_MIN_INSET_MM,
    PATTERN_SILHOUETTE_MM,
    PATTERN_SOURCE_SYNTHETIC,
    type PatternCurvatureReport,
    parseBottomPattern,
    patternCurvatureReport,
    syntheticBottomPattern,
} from "./bottom-pattern";
export {
    cdtInteriorPolygon,
    cdtPlanarBand,
    countOpenNonBoundaryEdges,
    DISH_BAND_MM,
    delaunayXY,
    insertConstraintEdges,
} from "./cdt-band";
export { assertIEdges, assertLibraryDisk, assertRemainingIEdges, libraryCdtInterior } from "./cdt-lib";
export {
    closedCurvatureRadii,
    fitClosedC2Spline,
    lowCurvatureStartIndex,
    resampleClosedBSpline,
    resampleClosedC2,
    resamplePolyline,
    rotateClosed,
    startAtLowCurvature,
    startAtPosteriorHeel,
} from "./curves";
export {
    applyMeasuredUnclamped,
    blendedFlareCurvature,
    blendedFlareDeg,
    CUP_BOWL,
    clampToBound,
    type DeviceTypePreset,
    FILLET_BOUNDS,
    FLARE_BOUNDS,
    type FlareProfileKind,
    type FlareRegionDiagnostic,
    LATERAL_FLANGE_BOUNDS,
    type MeasuredVsBoundRow,
    resolveWallDefaults,
    type WallRegionDefaults,
} from "./defaults";
export {
    extractPlantarSheet,
    extractStockWallModel,
    extractTopOnlyModel,
    extractTopSheet,
    matchedLoftCurves,
    sampleUvField,
} from "./extract";
export {
    FAIRED_CONTROL_DEFAULT,
    type FairedPattern,
    type FairedPatternInput,
    fairedPattern,
} from "./faired-pattern";
export { evaluateHeelCupGate } from "./hermite";
export {
    type ClassifiedHit,
    countSelfIntersections,
    formatSiBreakdown,
    type SelfIntersectionReport,
    type SiFrameLog,
    type WallSubClass,
} from "./intersect";
export {
    buildHermiteStations,
    countColumnPlanReversals,
    MIN_REAL_BOTTOM_FILLET_MM,
} from "./loft";
export { defaultsFromStockCurves, diagnoseFlareProfiles, measureRegionFeatures } from "./measure";
export {
    countDegenerateFaces,
    countJunctionBandSlivers,
    cupHeightAtU,
    dishInteriorDeltaMm,
    foldReport,
    generatedMinWallMm,
    groundDriftMm,
    hausdorffReport,
    heelInnerWidthAtU,
    maxVertexDeltaMm,
    measureReconFlareDeg,
    medialArchUpperWallFolds,
    meshVertexMinZ,
    minWallThicknessMm,
    outlineExactOnBMm,
    outlineRingDeviationMm,
    outlineSeamDihedrals,
    plantarFlatDeltaMm,
    reconstructionManifold,
    sheetBoundaryStats,
    stitchVertexDeltaMm,
    tieredHausdorffReport,
    topSurfaceDeltas,
    windingReport,
} from "./metrics";
export { applyCurveModifiers } from "./modifiers";
export {
    applyOutlineClean,
    cleanClosedLoop,
    mergeCloseOutlineStations,
    OUTLINE_COLLINEAR_MM,
    OUTLINE_DEDUPE_MM,
    OUTLINE_NUDGE_MM,
} from "./outline-clean";
export {
    assertInsideRim,
    clipperRoundInset,
    clipperUnion,
    hygieneBottomPattern,
    PATTERN_MIN_RADIUS_MM,
    PATTERN_RIM_CLEARANCE_MM,
} from "./pattern-hygiene";
export { assertNonCrossing, buildPlanformFrame } from "./planform";
export {
    assertPlantarDisk,
    buildGeneratedPlantar,
    collapseShortIEdges,
    collarSteiner,
    I_COLLAPSE_MM,
    I_SLIVER_ASPECT,
    inwardEdgeSteiner,
    makePlantarSampler,
    PLANTAR_MARGIN_MM,
    PLANTAR_STEINER_EDGE_MIN_MM,
    PLANTAR_STEINER_MM,
    PLANTAR_STEINER_OUTLINE_FRAC,
} from "./plantar-cdt";
export { type ReconstructOptions, reconstructProceduralWalls } from "./reconstruct";
export {
    assertClosedStationRing,
    assertPeriodicQuadStrip,
    RING_WRAP_MIN_MM,
    rotateStationRing,
} from "./ring-seam";
export {
    mapZoneFixtures,
    soleUvFrameFromOutline,
    soleUvFrameFromPolyline,
    ZONE_FIXTURES,
    zoneFixturesMapIdentically,
} from "./sole-uv";
export {
    CROSSING_WINDOW,
    columnSidewaysSkewMm,
    countPlanViewChordCrossings,
    FLARE_DEV_CAP_DEG,
    type FlareCapReport,
    mapLoopByMatchedFeatures,
    masterCurveRadii,
    pairAtNativeTop,
    pairByHarmonic,
    pairByOutwardRay,
    parameterOnClosedLoop,
    reparameterizeBArcLength,
    resampleBySmoothedParameter,
    retargetPlantarFromE,
    SKEW_LIMIT_MM,
    type StationPairing,
    smoothClosedParameters,
    smoothClosedToMinRadius,
    TB_SMOOTH_SIGMA_MM,
} from "./stations";
export type {
    BottomOutline,
    ClinicalWallReport,
    ColumnProfile,
    FoldReport,
    HausdorffReport,
    LateralFlangeParams,
    LoftOptions,
    PlanformFrame,
    S0ParityReport,
    S1GateRow,
    S1ParityReport,
    StockWallModel,
    TieredHausdorffReport,
    TopSurface,
    TrimCurve,
    UvHeightField,
    WallModelMode,
    WallProfile,
} from "./types";
export {
    DEFAULT_LOFT_N,
    FOLD_HARD_LIMIT_DEG,
    FOLD_WORST_LIMIT_DEG,
    HAUSDORFF_LIMIT_MM,
    S1_HAUSDORFF,
    S1_MIN_WALL_MM,
    S1_PROFILE_RESIDUAL_MM,
} from "./types";
