// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

export {
    ACROSS_STATION_MAX_DEG,
    ACROSS_STATION_P99_MAX_DEG,
    ALONG_JOINT_MAX_DEG,
    ASPECT_EVERYWHERE_MAX,
    ASPECT_LAST_STRIP_MAX,
    ASPECT_ROUND_MAX,
    ASPECT_ROUND_S1_MAX,
    applyPlantarBandZ,
    applyTangentBandZ,
    assertFilletStation,
    assertFilletWalk,
    assertOutsideRound,
    assertPieceSpacing,
    assertT0ClearsSheet,
    BAND_INSET_MIN_MM,
    BEZIER_HANDLE_FRAC,
    bLoopOutwardNormal,
    CHORD_RISE_MAX_DEG,
    COLUMN_PLANARITY_LIMIT_MM,
    COS_T_MIN,
    type ColumnFrame,
    type ColumnQuality,
    canonicalRoundPhi,
    clampFramesMinWall,
    clampR1ToBudget,
    columnHeading,
    constructArcLineArc,
    constructFillet,
    constructFilletFromF,
    constructOutsideRound,
    constructSweepRule,
    DPHI_L_MAX_DEG,
    enforceLastChordFloor,
    ensureColumnMinEdge,
    estimateBandInsetMm,
    evalCubicBezier,
    FIL_CHORD_S1_MIN,
    FILLET_ASSERT_EPS,
    FILLET_B_MAX_DEG,
    FILLET_B_MIN_DEG,
    FILLET_FIRST_STEP_MAX_RATIO,
    FILLET_FIRST_STEP_MIN_RATIO,
    FILLET_FIRST_STEP_NEIGHBOUR_FRAC,
    FILLET_LAST_ROW_FRAC,
    FILLET_PIECE_MIN_MM,
    FILLET_PSI_MAX_DEG,
    FILLET_PSI_MIN_DEG,
    FILLET_R_CAP_MM,
    FILLET_ROW_STEP_MIN_DEG,
    FILLET_STEP_MAX_DEG,
    FOREFOOT_INSET_MM,
    FRAME_ANGLE_LIMIT_DEG,
    FRAME_SMOOTH_ITERS,
    filletCenterAndF,
    filletPathTangents,
    filletPieceLengthMm,
    filletRadiusMm,
    filletWalkPhis,
    floorR2OnLastStep,
    G1_MAX_DEG,
    HANDLE_CHORD_CAP,
    HEADING_MAX_DEG,
    headingAllowanceDeg,
    incidentFaceTangent,
    inwardOfOutline,
    isCollapsedColumn,
    LAST_CHORD_FLOOR_MAX_FRAC,
    LAST_FILLET_S_MIN_MM,
    LAST_FILLET_Z_MIN_MM,
    LINE_MAX_STEP_MM,
    lastFilletCMinMm,
    lastFilletDLRad,
    lastFilletPhis,
    lastFilletR2MinMm,
    lastStepChordMm,
    limitNormalSteps,
    liveSheetAtR,
    lockFilletSteal,
    MERGE_ROW_MM,
    MIN_EDGE_MM,
    MIN_LINE_MM,
    type MinWallClamp,
    maxR2RowsForSweep,
    N_TOP_MAX_DEG,
    N_TOP_PATCH_MM,
    NEIGHBOUR_SPACING_RATIO,
    type NRoundStarReport,
    nTopFromSheetSlope,
    OUTLINE_STATION_SPACING_MM,
    offPlaneMm,
    PLANTAR_N_SMOOTH_SIGMA_MM,
    packAlaRadii,
    periodicGaussian,
    plantarFrameAt,
    plantarFrameFromNormal,
    R_ABS_RATE_MM,
    R_CHANGE_MAX_PCT,
    R_SMOOTH_FRAC,
    R1_HEIGHT_FRAC,
    R2_CHANGE_MAX_PCT,
    R2_RATE_LIMIT_PCT,
    RING_TURNING_MAX_DEG,
    ROUND_JOINT_ABORT_DEG,
    ROUND_JOINT_MAX_DEG,
    ROUND_START_INCIDENT_MAX_DEG,
    ROUND_SWEEP_SPLIT_DEG,
    rateLimitClosed,
    rateLimitClosedAbs,
    rateLimitClosedAbsRaise,
    rateLimitClosedDown,
    resolveLastR2,
    rimOverhangMm,
    rotateColumnAboutB,
    rowPieceId,
    SCALAR_SMOOTH_SIGMA_MM,
    SEAM_B_FALLBACK_DEG,
    SEAM_B_LIMIT_DEG,
    SEAM_B_SLACK_DEG,
    SECANT_FAR_MM,
    SECANT_NEAR_MM,
    SIDEWAYS_LIMIT_MM,
    SIGNED_FOLD_MAX_DEG,
    STATION_GAP_MULT,
    STEEP_SHEET_DEG,
    sampleByArcLength,
    sampleFilletPiecePoints,
    sampleInPlaneSlope,
    scaleShortWallPack,
    sheetSlopeFromNormal,
    sizedArcRows,
    slopeFromSheetPlane,
    smoothEPhi,
    smoothFRing,
    smoothPlantarNormalField,
    smoothRoundEndAngles,
    squareHeadingToB,
    summarizeWallBands,
    T0_LEAD_DROP_MM,
    T0_PIN_DEG,
    TOE_SPACING_EXTENT_FRAC,
    TOP_CLEARANCE_DEG,
    t0FromSheetSlope,
    t0LeadQ,
    t0TargetRad,
    tangentBandZ,
    topRoundRowCount,
    U_BANDS,
    type WallBandRow,
    WELD_MM,
    wallStartTiltRad,
} from "./bezier-column";
export {
    assertCutInOnHighRimSide,
    closedSignedCurvature,
    countClosedInflections,
    fairInsetMm,
    fairLateralInsetMm,
    INFLECTION_K_EPS,
    INFLECTION_MIN_ARC_MM,
    LATERAL_K_SLACK,
    type MedialYSign,
    makeLateralConvex,
    medialYSignFromPattern,
    medialYSignFromTopRim,
    movedPatternHygiene,
    PATTERN_ARCH_INSET_MM,
    PATTERN_BLEND_MM,
    PATTERN_CONTROL_COUNT,
    PATTERN_FEATURE_COUNT,
    PATTERN_FOREFOOT_INSET_MM,
    PATTERN_HEEL_INSET_MM,
    PATTERN_HEEL_LATERAL_INSET_MM,
    PATTERN_INSET_MM,
    PATTERN_MAX_DKDS,
    PATTERN_MIN_INSET_MM,
    PATTERN_SILHOUETTE_MM,
    PATTERN_SOURCE_SYNTHETIC,
    type PatternCurvatureReport,
    parseBottomPattern,
    patternCurvatureReport,
    syntheticBottomPattern,
} from "./bottom-pattern";
export {
    cdtInteriorPolygon,
    cdtPlanarBand,
    countOpenNonBoundaryEdges,
    DISH_BAND_MM,
    delaunayXY,
    insertConstraintEdges,
} from "./cdt-band";
export { assertIEdges, assertLibraryDisk, assertRemainingIEdges, libraryCdtInterior } from "./cdt-lib";
export {
    closedCurvatureRadii,
    fitClosedC2Spline,
    lowCurvatureStartIndex,
    nearestClosedArc01,
    resampleClosedBSpline,
    resampleClosedC2,
    resamplePolyline,
    rotateClosed,
    startAtLowCurvature,
    startAtPosteriorHeel,
} from "./curves";
export {
    applyMeasuredUnclamped,
    blendedFlareCurvature,
    blendedFlareDeg,
    CUP_BOWL,
    clampToBound,
    type DeviceTypePreset,
    FILLET_BOUNDS,
    FLARE_BOUNDS,
    type FlareProfileKind,
    type FlareRegionDiagnostic,
    LATERAL_FLANGE_BOUNDS,
    type MeasuredVsBoundRow,
    resolveWallDefaults,
    type WallRegionDefaults,
} from "./defaults";
export {
    extractPlantarSheet,
    extractStockWallModel,
    extractTopOnlyModel,
    extractTopSheet,
    matchedLoftCurves,
    sampleUvField,
} from "./extract";
export {
    FAIRED_CONTROL_DEFAULT,
    type FairedPattern,
    type FairedPatternInput,
    fairedPattern,
} from "./faired-pattern";
export { evaluateHeelCupGate, TOP_ROUND_MAX_STEP_DEG, TOP_ROUND_MIN_ROWS } from "./hermite";
export {
    type ClassifiedHit,
    countSelfIntersections,
    formatSiBreakdown,
    type SelfIntersectionReport,
    type SiFrameLog,
    type WallSubClass,
} from "./intersect";
export {
    buildHermiteStations,
    countColumnPlanReversals,
    MIN_REAL_BOTTOM_FILLET_MM,
} from "./loft";
export { defaultsFromStockCurves, diagnoseFlareProfiles, measureRegionFeatures } from "./measure";
export {
    countDegenerateFaces,
    countJunctionBandSlivers,
    cupHeightAtU,
    dishInteriorDeltaMm,
    foldReport,
    generatedMinWallMm,
    groundDriftMm,
    hausdorffReport,
    heelInnerWidthAtU,
    heelRegionWallHeightMm,
    maxVertexDeltaMm,
    measureReconFlareDeg,
    medialArchUpperWallFolds,
    meshVertexMinZ,
    minWallThicknessMm,
    outlineExactOnBMm,
    outlineRingDeviationMm,
    outlineSeamDihedrals,
    plantarFlatDeltaMm,
    reconstructionManifold,
    sheetBoundaryStats,
    stitchVertexDeltaMm,
    tieredHausdorffReport,
    topSurfaceDeltas,
    windingReport,
} from "./metrics";
export {
    applyCurveModifiers,
    clampPostingOnStations,
    clampPostingOnTopSheet,
    type ProceduralWallStyle,
    plantarNormalAt,
    plantarZDelta,
    postingZDelta,
} from "./modifiers";
export {
    applyOutlineClean,
    cleanClosedLoop,
    mergeCloseOutlineStations,
    OUTLINE_COLLINEAR_MM,
    OUTLINE_DEDUPE_MM,
    OUTLINE_NUDGE_MM,
} from "./outline-clean";
export {
    assertInsideRim,
    clipperRoundInset,
    clipperUnion,
    enforceMinRimInset,
    hygieneBottomPattern,
    PATTERN_MIN_RADIUS_MM,
    PATTERN_RIM_CLEARANCE_MM,
    RIM_INSET_SLACK_MM,
} from "./pattern-hygiene";
export { assertNonCrossing, buildPlanformFrame } from "./planform";
export {
    assertPlantarDisk,
    buildGeneratedPlantar,
    collapseShortIEdges,
    collarSteiner,
    faceMinAngleDeg,
    I_COLLAPSE_MM,
    I_SLIVER_ASPECT,
    inwardEdgeSteiner,
    makePlantarSampler,
    PLANTAR_MARGIN_MM,
    PLANTAR_STEINER_EDGE_MIN_MM,
    PLANTAR_STEINER_MM,
    PLANTAR_STEINER_OUTLINE_FRAC,
    SLIVER_MIN_ANGLE_DEG,
} from "./plantar-cdt";
export { type ReconstructOptions, reconstructProceduralWalls, splitAcuteTriangles } from "./reconstruct";
export {
    assertClosedStationRing,
    assertPeriodicQuadStrip,
    RING_WRAP_MIN_MM,
    rotateStationRing,
} from "./ring-seam";
export {
    mapZoneFixtures,
    soleUvFrameFromOutline,
    soleUvFrameFromPolyline,
    ZONE_FIXTURES,
    zoneFixturesMapIdentically,
} from "./sole-uv";
export {
    adjustPatternForClearance,
    allowedLeanRad,
    assertPostLoftGates,
    assertPreLoftStations,
    CLEARANCE_TARGET_WEIGHT,
    columnInsetSkew,
    fairedPlantarFromStock,
    fairMovedPattern,
    filletRadiiFromDefaults,
    LEAN_INSET_MM,
    LEAN_MAX_DEG,
    limitStationSkew,
    MIN_INSET_FLOOR_MM,
    minInsetAtStationMm,
    minInsetForLeanMm,
    PATTERN_SOURCE_FAIRED_STOCK,
    POSTLOFT_DIHEDRAL_MAX_DEG,
    PRELOFT_HEADING_MAX_DEG,
    scalePatternWidth,
    shiftPatternByRimFollow,
    signedRimInsetMm,
    smoothMovedStationOutline,
    stockTargetsForFairedPattern,
} from "./station-gates";
export {
    CROSSING_WINDOW,
    columnSidewaysSkewMm,
    countPlanViewChordCrossings,
    FLARE_DEV_CAP_DEG,
    type FlareCapReport,
    limitPairingSkew,
    mapLoopByMatchedFeatures,
    masterCurveRadii,
    pairAtNativeTop,
    pairByHarmonic,
    pairByOutwardRay,
    parameterOnClosedLoop,
    reparameterizeBArcLength,
    resampleBySmoothedParameter,
    retargetPlantarFromE,
    SKEW_INSET_RATIO,
    SKEW_LIMIT_MM,
    type StationPairing,
    smoothClosedParameters,
    smoothClosedToMinRadius,
    TB_SMOOTH_SIGMA_MM,
} from "./stations";
export type {
    BottomOutline,
    ClinicalWallReport,
    ColumnProfile,
    FoldReport,
    HausdorffReport,
    LateralFlangeParams,
    LoftOptions,
    PlanformFrame,
    S0ParityReport,
    S1GateRow,
    S1ParityReport,
    StockWallModel,
    TieredHausdorffReport,
    TopSurface,
    TrimCurve,
    UvHeightField,
    WallModelMode,
    WallProfile,
} from "./types";
export {
    DEFAULT_LOFT_N,
    FOLD_HARD_LIMIT_DEG,
    FOLD_WORST_LIMIT_DEG,
    HAUSDORFF_LIMIT_MM,
    S1_HAUSDORFF,
    S1_MIN_WALL_MM,
    S1_PROFILE_RESIDUAL_MM,
} from "./types";
export {
    acuteVecDeg,
    conicRowCountByTurning,
    cubicHasInflection,
    cubicRowCountByTurning,
    g1ControlPoint,
    g1OfConic,
    g1OfCubic,
    HYBRID_BLEND_MM,
    HYBRID_SWITCH_U_LATERAL,
    HYBRID_SWITCH_U_MEDIAL,
    hermiteControls,
    hybridBulgeAt,
    inflectionNormal,
    intersectTangentLines,
    type MidStyleSample,
    midStyleLambda,
    type PlanBoundReport,
    planAngleDeg,
    planBoundsOf,
    resolveWallStyleParams,
    sampleConicByTurning,
    sampleCubicByTurning,
    sampleWallMidStyle,
    stationBulge,
    WALL_BULGE_DEFAULT,
    WALL_LAMBDA_MIN,
    WALL_MID_DIHEDRAL_MAX_DEG,
    WALL_MID_TURN_MAX_DEG,
    WALL_MID_TURN_TARGET_DEG,
    WALL_PLAN_ANGLE_REPORT_DEG,
    WALL_PLAN_OUT_DEFAULT_MM,
    WALL_STYLE_ACROSS_P99_BLOCK_DEG,
    WALL_STYLE_ACROSS_P99_MAX_DEG,
    WALL_STYLE_ACROSS_P100_BLOCK_DEG,
    WALL_STYLE_G1_MAX_DEG,
    WALL_STYLE_G1_OUT_MAX_DEG,
    type WallStyleParams,
} from "./wall-style";
